name: firebase_ml_vision_example
description: Demonstrates how to use the firebase_ml_vision plugin.

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.5.0
  cupertino_icons: ^0.1.2
  firebase_ml_vision: any
  firebase_core: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/barcode_scanning.png
    - assets/images/face_detection.png
    - assets/images/image_labeling.png
    - assets/images/text_recognition.png
