const String SPLASH_SCREEN = 'SPLASH_SCREEN';
const String HOME_SCREEN = 'HOME_SCREEN';
const String TEXT_SCANNER = 'TEXT_SCANNER';
const String BARCODE_SCANNER = 'BARCODE_SCANNER';
const String LABEL_SCANNER = 'LABEL_SCANNER';
const String LABEL_SCANNER_CLOUD = 'LABEL_SCANNER_CLOUD';
const String FACE_SCANNER = 'FACE_SCANNER';
const String DETAIL_PAGE = 'HOME_SCREEN';
